# Constantes utilizadas na aplicação

BASE_HEXA = 16
BASE_DEC  = 10
BASE_BIN  = 2
BASE_SEGUNDOS = 60

PERIODICO_OK = 0
PERIODICO_ALARMADO = 1
CONFIGURACAO = 3
INICIALIZACAO = 4
LEITURA_INSTANTANEA = 5
CONTAGEM_ALARMAR = 7
NORMALIZACAO = 8
ALARME_INSTANTANEO = 9
ID_RECEBIDO = 9999


QTDE_ANALOGICAS = 16
QTDE_DIGITAIS   = 4
QTDE_NEGATIVAS  = 4

SIZE_PERIODICO_OK = 72
SIZE_CONFIGURACAO = 190
SIZE_PACOTES_DEFAULT = 88
SIZE_ID_TELEMETRIA = 4
